[package]
name = "quickfetch"
description = "A library built to fetch multiple requests quickly!"
version = "0.1.0"
edition = "2021"
rust-version = "1.78" # plan on using diagnostics
license = "MIT"
authors = ["Mustafif Khan"]

[[example]]
name = "mufiz"
path = "examples/mufiz.rs"

[[example]]
name = "mufiz_pkg"
path = "examples/mufiz_pkg.rs"

[dependencies]
anyhow = "1.0.86"
futures = "0.3.30"
reqwest = { version = "0.12.4", features = ["json", "brotli", "stream"] }
sled = "0.34.7"
tokio = { version = "1.37.0", features = ["full"] }
url = "2.5.0"
serde = { version = "1.0.203", features = ["derive"] }
log = "0.4.21"
pretty_env_logger = "0.5.0"
dirs = "5.0.1"
semver = "1.0.23"
bincode = "1.3.3"
serde_json = "1.0.117"
toml = "0.8.14"
bytes = "1.6.0"
