[[packages]]
name = "mufiz-rpm-aarch64"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.aarch64.rpm"
is_gh = true

[[packages]]
name = "mufiz-rpm-i386"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.i386.rpm"
is_gh = true

[[packages]]
name = "mufiz-rpm-mips"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.mips.rpm"
is_gh = true

[[packages]]
name = "mufiz-rpm-mips64"
version = "0.7.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.mips64.rpm"
is_gh = true

[[packages]]
name = "mufiz-rpm-mips64el"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.mips64el.rpm"
is_gh = true

[[packages]]
name = "mufiz-rpm-mipsel"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.mipsel.rpm"
is_gh = true
