[[packages]]
name = "mufiz-rpm-aarch64"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.aarch64.rpm"

[[packages]]
name = "mufiz-rpm-i386"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.i386.rpm"

[[packages]]
name = "mufiz-rpm-mips"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.mips.rpm"

[[packages]]
name = "mufiz-rpm-mips64"
version = "0.7.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.mips64.rpm"

[[packages]]
name = "mufiz-rpm-mips64el"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.mips64el.rpm"

[[packages]]
name = "mufiz-rpm-mipsel"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.mipsel.rpm"

[[packages]]
name = "mufiz-rpm-ppc"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.ppc.rpm"

[[packages]]
name = "mufiz-rpm-ppc64"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.ppc64.rpm"

[[packages]]
name = "mufiz-rpm-ppc64le"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.ppc64le.rpm"

[[packages]]
name = "mufiz-rpm-riscv64"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.riscv64.rpm"

[[packages]]
name = "mufiz-rpm-x86_64"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz-0.6.0-1.x86_64.rpm"

[[packages]]
name = "mufiz-zip-aarch64-linux-gnu"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_aarch64-linux-gnu.zip"

[[packages]]
name = "mufiz-zip-aarch64-linux-musl"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_aarch64-linux-musl.zip"

[[packages]]
name = "mufiz-zip-aarch64-linux"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_aarch64-linux.zip"

[[packages]]
name = "mufiz-zip-aarch64-macos"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_aarch64-macos.zip"

[[packages]]
name = "mufiz-zip-aarch64-windows-gnu"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_aarch64-windows-gnu.zip"

[[packages]]
name = "mufiz-zip-aarch64-windows"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_aarch64-windows.zip"

[[packages]]
name = "mufiz-deb-amd64"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_amd64.deb"

[[packages]]
name = "mufiz-zip-arm-linux-gnueabihf"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_arm-linux-gnueabihf.zip"

[[packages]]
name = "mufiz-zip-arm-linux-musleabihf"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_arm-linux-musleabihf.zip"

[[packages]]
name = "mufiz-deb-arm64"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_arm64.deb"

[[packages]]
name = "mufiz-deb-i386"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_i386.deb"

[[packages]]
name = "mufiz-zip-mips-linux-musl"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_mips-linux-musl.zip"

[[packages]]
name = "mufiz-deb-mips"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_mips.deb"

[[packages]]
name = "mufiz-zip-mips64-linux-musl"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_mips64-linux-musl.zip"

[[packages]]
name = "mufiz-deb-mips64"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_mips64.deb"

[[packages]]
name = "mufiz-zip-mips64el-linux-musl"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_mips64el-linux-musl.zip"

[[packages]]
name = "mufiz-deb-mips64el"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_mips64el.deb"

[[packages]]
name = "mufiz-zip-mipsel-linux-musl"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_mipsel-linux-musl.zip"

[[packages]]
name = "mufiz-deb-mipsel"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_mipsel.deb"

[[packages]]
name = "mufiz-zip-powerpc-linux-musl"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_powerpc-linux-musl.zip"

[[packages]]
name = "mufiz-zip-powerpc-linux"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_powerpc-linux.zip"

[[packages]]
name = "mufiz-deb-powerpc"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_powerpc.deb"

[[packages]]
name = "mufiz-zip-powerpc64-linux-gnu"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_powerpc64-linux-gnu.zip"

[[packages]]
name = "mufiz-zip-powerpc64-linux-musl"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_powerpc64-linux-musl.zip"

[[packages]]
name = "mufiz-zip-powerpc64-linux"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_powerpc64-linux.zip"

[[packages]]
name = "mufiz-deb-powerpc64"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_powerpc64.deb"

[[packages]]
name = "mufiz-zip-powerpc64le-linux-gnu"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_powerpc64le-linux-gnu.zip"

[[packages]]
name = "mufiz-zip-powerpc64le-linux-musl"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_powerpc64le-linux-musl.zip"

[[packages]]
name = "mufiz-zip-powerpc64le-linux"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_powerpc64le-linux.zip"

[[packages]]
name = "mufiz-deb-powerpc64le"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_powerpc64le.deb"

[[packages]]
name = "mufiz-zip-riscv64-linux-musl"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_riscv64-linux-musl.zip"

[[packages]]
name = "mufiz-zip-riscv64-linux"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_riscv64-linux.zip"

[[packages]]
name = "mufiz-deb-riscv64"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_riscv64.deb"

[[packages]]
name = "mufiz-zip-x86-linux-gnu"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_x86-linux-gnu.zip"

[[packages]]
name = "mufiz-zip-x86-linux-musl"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_x86-linux-musl.zip"

[[packages]]
name = "mufiz-zip-x86-linux"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_x86-linux.zip"

[[packages]]
name = "mufiz-zip-x86-windows-gnu"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_x86-windows-gnu.zip"

[[packages]]
name = "mufiz-zip-x86_64-linux-gnu"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_x86_64-linux-gnu.zip"

[[packages]]
name = "mufiz-zip-x86_64-linux-musl"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_x86_64-linux-musl.zip"

[[packages]]
name = "mufiz-zip-x86_64-linux"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_x86_64-linux.zip"

[[packages]]
name = "mufiz-zip-x86_64-macos"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_x86_64-macos.zip"

[[packages]]
name = "mufiz-zip-x86_64-windows-gnu"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_x86_64-windows-gnu.zip"

[[packages]]
name = "mufiz-zip-x86_64-windows"
version = "0.6.0"
url = "https://github.com/Mustafif/MufiZ/releases/download/v0.6.0/mufiz_0.6.0_x86_64-windows.zip"